### ISSUE TITLE
Compilation without CUDA seems not possible

### ISSUE THREAD

**Issue by martin-ueding** [fwinter/qdp-jit#13]
I am trying to compile QDP-JIT on a Haswell machine without GPUs. I have specified `--without-cuda` but from the `configure.ac` it makes the impression that this case was never expected and it is not handled. Am I doing something wrong or is CUDA a hard requirement for the compilation?

I have used the `master` branch as it seems more recent than `devel`. Or do I need to use any of the other branches for a CPU build?

**Comment by kostrzewa** [comment]
My guess would be that one would need to attempt to compile the [llvm-cpu-inner-loop-no11-qshift](https://github.com/fwinter/qdp-jit/tree/llvm-cpu-inner-loop-no11-qshift) branch, while for GPUs one would go with the [llvm-nvptx](https://github.com/fwinter/qdp-jit/tree/llvm-nvptx). Is the former what you tried?

**Comment by bjoo** [comment]
Hi Bartosz, 
 Yes, this is the choice of Branches. I would use llvm-5.0.0 for now to start with. I have compiled with a trunk version of LLVM-6 also (pre-release) 
The exact SVN ID for that is: 

> commit dbbb6c5fc3642987430866dffdf710df4f616ac7
> Author: Nirav Dave <niravd@google.com>
> Date:   Mon Nov 27 15:28:15 2017 +0000
> 
>     [DAG] Do MergeConsecutiveStores again before Instruction Selection
>     
>     Summary:
>     
>     Now that store-merge is only generates type-safe stores, do a second
>     pass just before instruction selection to allow lowered intrinsics to
>     be merged as well.
>     
>     Reviewers: jyknight, hfinkel, RKSimon, efriedma, rnk, jmolloy
>     
>     Subscribers: javed.absar, llvm-commits
>     
>     Differential Revision: https://reviews.llvm.org/D33675
>     
>     git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@319036 91177308-0d3

I have not yet tried LLVM-6.0.0 Release. 
Best, 
 B


> On Mar 26, 2018, at 12:07 PM, Bartosz Kostrzewa <notifications@github.com> wrote:
> 
> My guess would be that one would need to attempt to compile the llvm-cpu-inner-loop-no11-qshift branch, while for GPUs one would go with the llvm-nvptx. Is the former what you tried?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by martin-ueding** [comment]
I have used the LLVM 6.0.0 source, either from your “package” or from the LLVM website. And on JURECA I use Intel 2018 because the IntelMPI corresponding to Intel 2017 is a bit hidden.

LLVM has compiled fine, QDP-JIT in the appropriate branch has also compiled fine. Now it fails within QPhiX:

```
/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_reality.h(97): error: no operator "*=" matches these operands
            operand types are: QDP::Word<REAL> *= const double
        elem() *= rhs.elem();
               ^
          detected during:
            instantiation of "QDP::RScalar<T> &QDP::RScalar<T>::operator*=(const QDP::RScalar<T1> &) [with T=QDP::Word<REAL={REAL64={double}}>, T1=double]" at line 94 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_primscalar.h"
            instantiation of "QDP::PScalar<T> &QDP::PScalar<T>::operator*=(const QDP::PScalar<T1> &) [with T=QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>, T1=QDP::RScalar<double>]" at line 94 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_primscalar.h"
            instantiation of "QDP::PScalar<T> &QDP::PScalar<T>::operator*=(const QDP::PScalar<T1> &) [with T=QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>, T1=QDP::PScalar<QDP::RScalar<double>>]" at line 591 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/PETE/OperatorTags.h"
            instantiation of "QDP::BinaryReturn<T1, T2, QDP::OpMultiplyAssign>::Type_t QDP::OpMultiplyAssign::operator()(const T1 &, const T2 &) const [with T1=QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>>, T2=QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>]" at line 245 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_outer.h"
            instantiation of "void QDP::evaluate(QDP::OScalar<T> &, const Op &, const QDP::QDPExpr<RHS, QDP::OScalar<T1>> &, const QDP::Subset &) [with T=QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>>, T1=QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, Op=QDP::OpMultiplyAssign, RHS=QDP::BinaryNode<QDP::OpMultiply, QDP::Reference<QDP::QDPType<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>>>,
                      QDP::Reference<QDP::QDPType<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>>>>]" at line 173 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_qdptype.h"
            instantiation of "C &QDP::QDPType<T, C>::operator*=(const QDP::QDPExpr<T1, C1> &) [with T=QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>>, C=QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>>>, T1=QDP::BinaryNode<QDP::OpMultiply, QDP::Reference<QDP::QDPType<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>>>,
                      QDP::Reference<QDP::QDPType<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>>>>, C1=QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>]" at line 168 of "/homec/hbn28/hbn28e/Chroma-JIT/sources/qphix/tests-gtest/../tests/./clover_term_qdp_w.h"
            instantiation of "void QPhiX::QDPCloverTermT<T, U>::create(const QDP::multi1d<U> &, const CloverFermActParams &) [with T=QDP::LatticeFermion, U=QDP::LatticeColorMatrix]" at line 204 of "/homec/hbn28/hbn28e/Chroma-JIT/sources/qphix/tests-gtest/../tests/RandomGauge.h"
            instantiation of "void QPhiX::RandomGauge<FT, veclen, soalen, compress12, QdpGauge_, QdpSpinor_>::init_clover() [with FT=double, veclen=1, soalen=1, compress12=false, QdpGauge_=QDP::LatticeColorMatrixD, QdpSpinor_=QDP::LatticeDiracFermionD]" at line 145 of "/homec/hbn28/hbn28e/Chroma-JIT/sources/qphix/tests-gtest/../tests/RandomGauge.h"
            instantiation of "QPhiX::RandomGauge<FT, veclen, soalen, compress12, QdpGauge_, QdpSpinor_>::RandomGauge(QPhiX::Geometry<FT, veclen, soalen, compress12> &, double, double) [with FT=double, veclen=1, soalen=1, compress12=false, QdpGauge_=QDP::LatticeColorMatrixD, QdpSpinor_=QDP::LatticeDiracFermionD]" at line 23 of "/homec/hbn28/hbn28e/Chroma-JIT/sources/qphix/tests-gtest/random_gauge.cc"
```

Is this the error that we talked about months ago with the `RandomGauge` not working together with QDP-JIT?

**Comment by bjoo** [comment]
Hi Martin, 
 This may well be the error, tho I must admit to not having tried compiling with Intel 2018, because, when compiling regular QDP++ (not JIT) with QPhiX Intel-2018 threw internal errors in the
process (I can’t recall whether it was in QDP++ or QPhiX). I have also in the past seen funnies with Chroma’s regression tests when using Intel-2017 (again, without JIT). For this reason, 
 my preferred compiler is still Intel-16.

Best, 
 B
> On Mar 27, 2018, at 6:20 AM, Martin Ueding <notifications@github.com> wrote:
> 
> I have used the LLVM 6.0.0 source, either from your “package” or from the LLVM website. And on JURECA I use Intel 2018 because the IntelMPI corresponding to Intel 2017 is a bit hidden.
> 
> LLVM has compiled fine, QDP-JIT in the appropriate branch has also compiled fine. Now it fails within QPhiX:
> 
> /homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_reality.h(97): error: no operator "*=" matches these operands
>             operand types are: QDP::Word<REAL> *= const double
>         elem() *= rhs.elem();
>                ^
>           detected during:
>             instantiation of "QDP::RScalar<T> &QDP::RScalar<T>::operator*=(const QDP::RScalar<T1> &) [with T=QDP::Word<REAL={REAL64={double}}>, T1=double]" at line 94 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_primscalar.h"
>             instantiation of "QDP::PScalar<T> &QDP::PScalar<T>::operator*=(const QDP::PScalar<T1> &) [with T=QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>, T1=QDP::RScalar<double>]" at line 94 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_primscalar.h"
>             instantiation of "QDP::PScalar<T> &QDP::PScalar<T>::operator*=(const QDP::PScalar<T1> &) [with T=QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>, T1=QDP::PScalar<QDP::RScalar<double>>]" at line 591 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/PETE/OperatorTags.h"
>             instantiation of "QDP::BinaryReturn<T1, T2, QDP::OpMultiplyAssign>::Type_t QDP::OpMultiplyAssign::operator()(const T1 &, const T2 &) const [with T1=QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>>, T2=QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>]" at line 245 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_outer.h"
>             instantiation of "void QDP::evaluate(QDP::OScalar<T> &, const Op &, const QDP::QDPExpr<RHS, QDP::OScalar<T1>> &, const QDP::Subset &) [with T=QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>>, T1=QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, Op=QDP::OpMultiplyAssign, RHS=QDP::BinaryNode<QDP::OpMultiply, QDP::Reference<QDP::QDPType<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>>>,
>                       QDP::Reference<QDP::QDPType<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>>>>]" at line 173 of "/homec/hbn28/hbn28e/Chroma-JIT/local-icc/include/qdp_qdptype.h"
>             instantiation of "C &QDP::QDPType<T, C>::operator*=(const QDP::QDPExpr<T1, C1> &) [with T=QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>>, C=QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<REAL={REAL64={double}}>>>>>, T1=QDP::BinaryNode<QDP::OpMultiply, QDP::Reference<QDP::QDPType<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>>>,
>                       QDP::Reference<QDP::QDPType<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>, QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>>>>, C1=QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<double>>>>]" at line 168 of "/homec/hbn28/hbn28e/Chroma-JIT/sources/qphix/tests-gtest/../tests/./clover_term_qdp_w.h"
>             instantiation of "void QPhiX::QDPCloverTermT<T, U>::create(const QDP::multi1d<U> &, const CloverFermActParams &) [with T=QDP::LatticeFermion, U=QDP::LatticeColorMatrix]" at line 204 of "/homec/hbn28/hbn28e/Chroma-JIT/sources/qphix/tests-gtest/../tests/RandomGauge.h"
>             instantiation of "void QPhiX::RandomGauge<FT, veclen, soalen, compress12, QdpGauge_, QdpSpinor_>::init_clover() [with FT=double, veclen=1, soalen=1, compress12=false, QdpGauge_=QDP::LatticeColorMatrixD, QdpSpinor_=QDP::LatticeDiracFermionD]" at line 145 of "/homec/hbn28/hbn28e/Chroma-JIT/sources/qphix/tests-gtest/../tests/RandomGauge.h"
>             instantiation of "QPhiX::RandomGauge<FT, veclen, soalen, compress12, QdpGauge_, QdpSpinor_>::RandomGauge(QPhiX::Geometry<FT, veclen, soalen, compress12> &, double, double) [with FT=double, veclen=1, soalen=1, compress12=false, QdpGauge_=QDP::LatticeColorMatrixD, QdpSpinor_=QDP::LatticeDiracFermionD]" at line 23 of "/homec/hbn28/hbn28e/Chroma-JIT/sources/qphix/tests-gtest/random_gauge.cc"
> 
> Is this the error that we talked about months ago with the RandomGauge not working together with QDP-JIT?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------
