### ISSUE TITLE
Specialization for WordType<C> for C=QDP::OScalar<QDP::PSpinMatrix<QDP::PScalar<QDP::RComplex<QDP::Word<REAL={REAL32={float}}>>>, 4>> is missing

### ISSUE THREAD

**Issue by martin-ueding** [fwinter/qdp-jit#5]
I have just cloned the repository and tried to compile the `master` branch on JURECA, an Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz system with Intel C++ version 17.

Configuration was done using

```
$sourcedir/$repo/configure --prefix=$prefix --disable-shared --enable-static CC=$cc CXX=$cxx \                                   
        --enable-openmp \                                                          
        --enable-parallel-arch=parscalar \                                         
        --enable-parallel-io \                                                     
        --enable-sse --enable-sse2 \                                               
        --with-libxml2="$prefix/bin/xml2-config" \                                 
        --with-qmp="$prefix" \                                                     
        CFLAGS="$cflags" CXXFLAGS="$cxxflags"
```
where `$cflags` and `$cxxflags` are `-O2 -Wall -fopenmp` and for C++ also `--std=c++11`, `cc` and `cxx` are the paths to the MPI wrappers of Intel C++ compilers.

It seems that there is a template specification of `WordType` for the type `QDP::OScalar<QDP::PSpinMatrix<QDP::PScalar<QDP::RComplex<QDP::Word<REAL={REAL32={float}}>>>, 4>>` is missing.

```
depbase=`echo qdp_map.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/usr/local/software/jureca/Stages/2016b/software/impi/2017.0.098-iccifort-2017.0.098-GCC-5.4.0/bin64/mpiicpc -DHAVE_CONFIG_H -I. -I/homec/hbn28/hbn28e/Sources/qdp-jit/lib -I../include    -I/homec/hbn28/hbn28e/Sources/qdp-jit/include -I../include -I/homec/hbn28/hbn28e/Sources/qdp-jit/other_libs/qio/include -I../other_libs/qio/include -I/homec/hbn28/hbn28e/Sources/qdp-jit/other_libs/qio/other_libs/c-lime/include -I../other_libs/qio/other_libs/c-lime/include -I/homec/hbn28/hbn28e/Sources/qdp-jit/other_libs/xpath_reader/include -I/homec/hbn28/hbn28e/Sources/qdp-jit/other_libs/libintrin/include -I../other_libs/libintrin/include  -I/homec/hbn28/hbn28e/local-jureca/include/libxml2 -I/homec/hbn28/hbn28e/local-jureca/include  -I/usr/local/cuda/include -O2 -Wall -fopenmp --std=c++11 -MT qdp_map.o -MD -MP -MF $depbase.Tpo -c -o qdp_map.o /homec/hbn28/hbn28e/Sources/qdp-jit/lib/qdp_map.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /homec/hbn28/hbn28e/Sources/qdp-jit/include/qdp.h(187),
                 from /homec/hbn28/hbn28e/Sources/qdp-jit/lib/qdp_map.cc(8):
/homec/hbn28/hbn28e/Sources/qdp-jit/include/qdp_qdptype.h(51): error: incomplete type is not allowed
    C& assign(const typename WordType<C>::Type_t& rhs)
                             ^
          detected during:
            instantiation of class "QDP::QDPType<T, C> [with T=QDP::PSpinMatrix<QDP::PScalar<QDP::RComplex<QDP::Word<REAL={REAL32={float}}>>>, 4>, C=QDP::OScalar<QDP::PSpinMatrix<QDP::PScalar<QDP::RComplex<QDP::Word<REAL={REAL32={float}}>>>, 4>>]" at line 35 of "/homec/hbn28/hbn28e/Sources/qdp-jit/include/qdp_outer.h"
            instantiation of class "QDP::OScalar<T> [with T=QDP::PSpinMatrix<QDP::PScalar<QDP::RComplex<QDP::Word<REAL={REAL32={float}}>>>, 4>]" at line 243 of "/homec/hbn28/hbn28e/Sources/qdp-jit/include/qdp_outer.h"
```

The definition of `WordType` has a comment stating that the user must give the appropriate specialization for a container to participate in the JIT compilation process. Looking through the code I was able to find the specialization for `OScalar` in `include/qdp_outer.h`:

```c++
template<class T>
struct WordType<OScalar<T> > 
{
  typedef typename WordType<T>::Type_t  Type_t;
};
```

This seems to be a recursive template thing, there must be specializations all the way down to get to the one where it actually is a pre-defined type. The stack that must be traversed is this here:

- `QDP::OScalar`
- `QDP::PSpinMatrix`
- `QDP::PScalar`
- `QDP::RComplex`
- `QDP::Word`
- `float`

The next level is the `PSpinMatrix` which also has a specialization in `include/qdp_primspinmat.h`:

```c++
template<class T1, int N>
struct WordType<PSpinMatrix<T1,N> > 
{
  typedef typename WordType<T1>::Type_t  Type_t;
};
```

Then `PScalar` in `include/qdp_primscalar.h`:

```c++
template<class T>
struct WordType<PScalar<T> > 
{
  typedef typename WordType<T>::Type_t  Type_t;
};
```

There is `RComplex` in `include/qdp_reality.h`. The compiler cannot resolve that from `lib/qdp_map.cc` it seems. Somehow the following files need to be included into `lib/qdp_map.cc`:

- `include/qdp_primscalar.h`
- `include/qdp_reality.h`
- `include/qdp_primspinmat.h`
- `include/qdp_outer.h`
- `include/qdp_qdptype.h`

In order to quickly check whether all those are there, I added the following to `lib/qdp_map.cc`:

```c++
#if !defined(QDP_QDPTYPE_H) || !defined(QDP_PRIMSCALAR_H) \                     
     || !defined(QDP_REALITY_H) || !defined(QDP_PRIMSPINMAT_H) \                
     || !defined(QDP_OUTER_H)                                                    
 #error "Not all includes are there."                                            
#endif
```

`icpc` still complains about the “incomplete type”. Therefore the includes are there, but it still does not check out. I have added `-H` to the `icpc` call to see all the included files. All the files I have listed are properly included, so the error must be somewhere else.

What am I doing wrong for the compilation?

**Comment by fwinter** [comment]
The master branch's codegen targets PTX. With intel try the llvm-cpu-inner-loop-no11-qshift branch instead.

**Comment by martin-ueding** [comment]
Thank you!
